# Environment variables that are common across every CI/CD step
variables:
  DOCKER_IMAGE: pytest-project

.deployment_image:
  after_script:
    - docker-compose -f ./test/docker/docker-compose.yml down &>/dev/null || true
    - docker rm -v $(docker ps --filter status=exited -q | grep -v -E $(docker ps -aq --filter='name=runner' | paste -sd "|" -) 2>/dev/null) &>/dev/null || true
    - docker rmi $(docker images | grep "none" | awk '/ / { print $3 }') &>/dev/null || true
    - docker rmi $(docker images --filter dangling=true -q 2>/dev/null) &>/dev/null || true
    - docker network rm $(docker network ls --filter type=custom -q 2>/dev/null) &>/dev/null || true

stages:
  - test

# Run all tests
test:e2e:
  extends: .deployment_image
  allow_failure: true
  resource_group: test-e2e
  stage: test
  tags:
    - docker
  only:
    - schedule
  script:
    - ./run-tests.sh
  artifacts:
    expire_in: 1 month
    paths:
      - reports/*.xml
      - reports/*.html
    reports:
      junit: reports/*.xml
